# Generated by Django 5.2.15 on 2026-08-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_invoiceitem_description_invoiceitem_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='doctor_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_ammount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_ammount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_ammount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
