# Generated by Django 5.2.15 on 2026-07-06 18:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('record_type', models.CharField(choices=[('consultation', 'Consultation'), ('diagnosis', 'Diagnosis'), ('prescription', 'Prescription'), ('lab_result', 'Lab Result'), ('radiology', 'Radiology Report'), ('procedure', 'Procedure'), ('surgery', 'Surgery'), ('vital_signs', 'Vital Signs'), ('allergy', 'Allergy'), ('immunization', 'Immunization'), ('medication', 'Medication Record'), ('progress_note', 'Progress Note'), ('discharge_summary', 'Discharge Summary'), ('referral', 'Referral'), ('emergency', 'Emergency Record'), ('follow_up', 'Follow Up'), ('medical_certificate', 'Medical Certificate'), ('other', 'Other')], default='consultation')),
                ('diagnosis', models.TextField()),
                ('notes', models.TextField()),
                ('file_url', models.FileField(blank=True, null=True, upload_to='medical_records')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('diagnosis', models.TextField()),
                ('notes', models.TextField()),
                ('follow_up_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosages', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
            ],
        ),
    ]
