# Generated by Django 5.2.15 on 2026-09-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='follow_up_date',
            field=models.DateTimeField(),
        ),
    ]
