# Generated by Django 5.2.15 on 2026-07-06 18:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('schelued_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked IN'), ('in_progress', 'IN Progress'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('no_show', 'NO Show'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('reason', models.CharField(max_length=500)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
