# Generated by Django 5.2.15 on 2026-07-24 19:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0003_alter_appointment_notes_and_more'),
        ('payments', '0003_invoice_doctor_fee_invoice_test_fee'),
        ('users', '0006_alter_patient_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('sample_pending', 'Sample Pending'), ('sample_collected', 'Sample Collected'), ('in_lab', 'In Lab'), ('processing', 'Processing'), ('report_ready', 'Report Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField()),
                ('total_ammount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='users.doctor')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='payments.invoice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TestOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=50)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('instruction', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sample_pending', 'Sample Pending'), ('sample_collected', 'Sample Collected'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending')),
                ('test_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tests.testorder')),
            ],
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('result', models.TextField()),
                ('file', models.FileField(upload_to='test_reports/')),
                ('remarks', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('test_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='tests.testorderitem')),
            ],
        ),
    ]
