# Generated by Django 5.2.15 on 2026-07-06 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('generic_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('analgesic', 'Analgesic'), ('antibiotic', 'Antibiotic'), ('antipyretic', 'Antipyretic'), ('antihistamine', 'Antihistamine'), ('anti_inflammatory', 'Anti-inflammatory'), ('antacid', 'Antacid'), ('antiviral', 'Antiviral'), ('antifungal', 'Antifungal'), ('antiparasitic', 'Antiparasitic'), ('antidiabetic', 'Antidiabetic'), ('antihypertensive', 'Antihypertensive'), ('cardiovascular', 'Cardiovascular'), ('respiratory', 'Respiratory'), ('gastrointestinal', 'Gastrointestinal'), ('dermatological', 'Dermatological'), ('vitamin_supplement', 'Vitamin & Supplement'), ('hormonal', 'Hormonal'), ('vaccine', 'Vaccine'), ('other', 'Other')], default='analgesic')),
                ('unit', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('bottle', 'Bottle'), ('tube', 'Tube'), ('vial', 'Vial'), ('ampoule', 'Ampoule'), ('sachet', 'Sachet'), ('pack', 'Pack'), ('strip', 'Strip'), ('piece', 'Piece'), ('roll', 'Roll'), ('other', 'Other')], default='tablet')),
                ('manufacturer', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiary_date', models.DateField()),
                ('reorder_level', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='medicines.medicine')),
            ],
        ),
    ]
